[package]
name = "priede-cli"
version = "0.1.0"
edition = "2021"


[dependencies]
interpreter = {path = "../interpreter"}
arguments = "*"
colored = "2.1.0"
clap = { version = "4.5.9", features = ["derive"] }

