// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQQOPOOO`OPO'#CaOOOO'#Cf'#CfOOOO'#Cd'#CdQQOPOOOOOO,58{,58{OqOPO,58{OOOO-E6b-E6bOOOO1G.g1G.g",
  stateData: "!S~OQQORQOSQOUPO~OQQORQOSQOUPOVTO~OQQORQOSQOUPOVWO~O",
  goto: "rZPPPPP[PPbPlXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ Program Identifier String Boolean Application ( )",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "$S~RWrskst#Xxy#gyz#l!Q![#q!c!}#q#R#S#q#T#o#q~nVOrkrs!Ts#Ok#O#P!Y#P;'Sk;'S;=`#R<%lOk~!YOR~~!]RO;'Sk;'S;=`!f;=`Ok~!iWOrkrs!Ts#Ok#O#P!Y#P;'Sk;'S;=`#R;=`<%lk<%lOk~#UP;=`<%lk~#[Q#Y#Z#b#h#i#b~#gOS~~#lOU~~#qOV~~#vSQ~!Q![#q!c!}#q#R#S#q#T#o#q",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
