// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Identifier = 3,
  String = 4,
  Operator = 8,
  VarType = 9,
  Number = 10,
  Bool = 11,
  Keyword = 12
